<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome', [
        'name' => 'Rene',
        'number' => request('id') // to get a request parameter
    ]);
});

Route::get('/about', function () {
    return view('about');
});

Route::get('/contact', function () {
    return view('contact');
});

// view generated by a Controller
Route::get('/tasks', 'TasksController@getAll');
Route::post('/tasks', 'TasksController@create');
Route::get('/tasks/{id}/toggleComplete', 'TasksController@toggleComplete');
Route::get('/tasks/{id}/edit', 'TasksController@edit');
Route::patch('/tasks/{id}', 'TasksController@update');
Route::delete('/tasks/{id}', 'TasksController@delete');

// generate all RESTful routes 
// Route::resource(‘tasks’, ‘AutoGenTasksController’);


